apiVersion: v1
data:
  ILP_SECRET_SEED: {{ .Values.config.secret_seed | required "Value config.secret_seed can not be empty!" | quote }}
  ILP_ADMIN_AUTH_TOKEN: {{ .Values.config.admin_auth_token | required "Value config.admin_auth_token can not be empty!" }}
  ILP_ADDRESS: {{ .Values.config.ilp_address }}
  ILP_DATABASE_URL: {{ .Values.config.database_url }}
  ILP_HTTP_BIND_ADDRESS: '{{ .Values.config.http_server.address }}:{{ .Values.config.http_server.port }}'
  ILP_SETTLEMENT_API_BIND_ADDRESS: {{ .Values.config.settlement_api_bind_address }}
  ILP_DEFAULT_SPSP_ACCOUNT: {{ .Values.config.default_spsp_account }}
  ILP_ROUTE_BROADCAST_INTERVAL: {{ .Values.config.route_broadcast_interval }}
  ILP_EXCHANGE_RATE__PROVIDER: {{ .Values.config.exchange_rate.provider }}
  ILP_EXCHANGE_RATE__POLL_INTERVAL: {{ .Values.config.exchange_rate.poll_interval }}
  ILP_EXCHANGE_RATE__SPREAD: {{ .Values.config.exchange_rate.spread }}
  ILP_PROMETHEUS__BIND_ADDRESS: {{ .Values.config.prometheus.bind_address }}
  ILP_PROMETHEUS__HISTOGRAM_WINDOW: {{ .Values.config.prometheus.histogram_window }}
  ILP_PROMETHEUS__HISTOGRAM_GRANULARITY: {{ .Values.config.prometheus.histogram_granularity }}
kind: ConfigMap
metadata:
  name: {{ include "interledger-rs.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "interledger-rs.name" . }}
