apiVersion: v1
kind: Service
metadata:
  name: {{ include "interledger-rs.name" . }}
  labels:
    app: {{ include "interledger-rs.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.config.http_server.port }}
  selector:
    app: {{ include "interledger-rs.name" . }}